@startuml
'https://plantuml.com/sequence-diagram

autonumber

DefaultMQProducer -> DefaultMQProducerImpl: send()
DefaultMQProducerImpl -> DefaultMQProducerImpl: sendDefaultImpl()
group sendDefaultImpl()

end

Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml